### ISSUE TITLE
Using Firefox instead of Chrome

### ISSUE THREAD

**Issue by ZeroCool940711** [LjMario007/Microsoft-Rewards-Bot#19]
Is there anyway to change the bot to use Firefox instead of Chrome?
I do not want to install chrome just to run this, also Ive read that chrome driver is broken on the latest version.

**Comment by velotoxicsounds** [comment]
I've already started a pull. I fixed the problem

**Comment by LjMario007** [comment]
I merged @velotoxicsounds’ PR (https://github.com/LjMario007/Microsoft-Rewards-Bot/pull/21), so can we close this?
