### ISSUE TITLE
The Future of Microsoft Rewards Bot

### ISSUE THREAD

**Issue by LjMario007** [LjMario007/Microsoft-Rewards-Bot#3]
Hey all,
I originally forked this repo from @xMNG just to make a couple customizations for my own use, but I'm more than happy to have it serve as the main repo, considering that @xMNG deleted the original repository. As per [this pull request](https://github.com/LjMario007/Microsoft-Rewards-Bot/pull/2), I added @andrewjmetzger as a collaborator, and I think I'll maybe turn on some CI/code quality stuff as well. I don't know why issues were turned off; they're on now. Do y'all have any other suggestions or ideas?

**Comment by LjMario007** [comment]
Also, should we use Codacy or CodeFactor for code quality checking?

**Comment by andrewjmetzger** [comment]
I have no preference in terms of provider. Look into GitHub Actions, I think it was (at least kind of) designed to help with this sort of QA check. Another option is [Code Climate for Quality](https://codeclimate.com/quality/), which grades protects' code on a scale from A+ (great) to F (horrible); it's free for open-source projects.

**Comment by LjMario007** [comment]
I attempted to make an Action to automatically format the code with Black, but it didn't really work. Currently both Codacy and CodeFactor are enabled, and I have another tool enabled to automatically check that the correct code style is used in all pull requests, and then automatically make another pull request with the style fixed(if necessary).

**Comment by andrewjmetzger** [comment]
That sounds complicated. I wonder if there's a way to simplify the process?

**Comment by LjMario007** [comment]
I'll think I'll just tun off CodeFactor, and just use Codacy for code quality, and Restlyled.io for checking pull requests.

**Comment by andrewjmetzger** [comment]
Codacy seems to be able to check PRs, too. What's the advantage to also using Restyled.io? Does Codacy apply fixes automatically?

**Comment by LjMario007** [comment]
Restyled.io just checks code formatting, but can automatically fix the issues it finds, whereas Codacy can find much more issues, but can't automatically fix them.

**Comment by andrewjmetzger** [comment]
Okay. At some point Soon™ I'll take a look at the settings for both to see if we can get them to play nicely together.

**Comment by JohnFortniteKennedy-skrt** [comment]
While using the bot it is doing way more searches than necessary I have it set to 32 max for PC and it will do to many and makes it take like 20 minutes to do my account.
