### ISSUE TITLE
Update! Fixed all bugs. Telegram Bot Integrated, point display functional

### ISSUE THREAD

**Issue by velotoxicsounds** [LjMario007/Microsoft-Rewards-Bot#61]
Hello,

the bot is currently running error-free with my fork! [https://github.com/LjMario007/Microsoft-Rewards-Bot/pull/59]

I have fixed the following points: 
- Points display works again
- Telegram Bot integration [Also transmits score via Telegram]
- General element bug fixed
- Advanced login screen fixed

I have planned the following:
Rework code, human activity
All languages are supported because Bot works via XPath.

**Comment by hidingfromu** [comment]
Hi Velotoxicsounds,

I'm based in the UK, and your version gives me less errors than other versions, but it still won't detect the current points total, so it does 150 searches for PC and Mobile resulting in 2 hours+ for 1 account to complete.

**Comment by velotoxicsounds** [comment]
Yes, I have the problem at the moment. Microsoft seems to be blocking the mobile requests in a new way. I just reworked my version and made the login error of LjMario007
as well as the points display. Just keep an eye on my REPO. As soon as I have a fix for the mobile agent I create a new push

**Comment by keepthecyphe** [comment]
@velotoxicsounds your code kept getting the pc and mobile points mixed up for me 
2020-10-25 13:09:36,772 :: INFO :: root :: PC points = 100/100
2020-10-25 13:09:36,772 :: INFO :: root :: Edge points = 100/100
2020-10-25 13:09:36,772 :: INFO :: root :: Mobile points = 0/150
(PC should be 150 and Mobile is 100) so whenever I ran a pc flag it would not run the searches concluding it was already completed. I just flipped it around in your get_point_total function try statement and it was good after that. 

You may want to consider opening the issues tab on your own repo as to not hijack @LjMario007's

**Comment by velotoxicsounds** [comment]
Yes I'm doing it here, I have an update to my repo, please test the version. If the error still exists after that please open a Chase
__

—

**Comment by hidingfromu** [comment]
> @velotoxicsounds your code kept getting the pc and mobile points mixed up for me
> 2020-10-25 13:09:36,772 :: INFO :: root :: PC points = 100/100
> 2020-10-25 13:09:36,772 :: INFO :: root :: Edge points = 100/100
> 2020-10-25 13:09:36,772 :: INFO :: root :: Mobile points = 0/150
> (PC should be 150 and Mobile is 100) so whenever I ran a pc flag it would not run the searches concluding it was already completed. I just flipped it around in your get_point_total function try statement and it was good after that.
> 
> You may want to consider opening the issues tab on your own repo as to not hijack @LjMario007's

Hi,

Which parts did you swap around? I am still having this issue, and even though it lists the total score in the worng place it is still performing searches until it hits 150. Cheers

**Comment by velotoxicsounds** [comment]
II haven't exchanged anything. I don't have an ID evaluation but refer to the direct xpath. That's why it works now. Can be seen at the get points function

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by hidingfromu** [comment]
Yeah PC doesn't work at all now, no matter what I put in. Mobile will rush to 60/60 even on --pc , but pc won't even move if I put in --mobile

**Comment by keepthecyphe** [comment]
> > @velotoxicsounds your code kept getting the pc and mobile points mixed up for me
> > 2020-10-25 13:09:36,772 :: INFO :: root :: PC points = 100/100
> > 2020-10-25 13:09:36,772 :: INFO :: root :: Edge points = 100/100
> > 2020-10-25 13:09:36,772 :: INFO :: root :: Mobile points = 0/150
> > (PC should be 150 and Mobile is 100) so whenever I ran a pc flag it would not run the searches concluding it was already completed. I just flipped it around in your get_point_total function try statement and it was good after that.
> > You may want to consider opening the issues tab on your own repo as to not hijack @LjMario007's
> 
> Hi,
> 
> Which parts did you swap around? I am still having this issue, and even though it lists the total score in the worng place it is still performing searches until it hits 150. Cheers

in ms_rewards.py, 
swap current_pc_points, max_pc_points in line 850 with current_mobile_points, max_mobile_points in line 853
