### ISSUE TITLE
Starting 03-04-2021 it stopped functioning.

### ISSUE THREAD

**Issue by BloodAsp** [LjMario007/Microsoft-Rewards-Bot#72]
Hi all, I likely don't have the correct information to provide to trouble shoot this yet, but this is what I have:
I'm on OS: Ubuntu 20.04.2 LTS x86_64,  Kernel: 5.8.0-44-generic, and have recently restarted the machine to make sure there are not hitches.
I noticed yesterday that my crontab process ran it, but it did not function, nor did it today.  So I tried it manually.  What it does is waits a bit, flickers the screen once, and then the processes is over.  When I tried to sudo python3 ms_rewards.py --pc , it gives me this:  
Traceback (most recent call last):
  File "ms_rewards.py", line 20, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

So I went into python3 and performed: >>> help (selenium)  , which gives me:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'selenium' is not defined

Which is defiantly weird, I hadn't removed selenium, or anything else.  I tried to import selenium.  It seemed to stick until I re-entered python3 again.

Later tonight I might try to find the proper debug info, and or rebuild from scratch. Any ideas on this?

**Comment by MortalPete** [comment]
You need to update Google Chrome. The bot updates the chromedriver but never the browser, which creates the conflict.

**Comment by BloodAsp** [comment]
> You need to update Google Chrome. The bot updates the chromedriver but never the browser, which creates the conflict.

I am on the latest version of chrome, Version 89.0.4389.72 (Official Build) (64-bit), and all my packages are up to date.
"0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded."

Out of curiosity, I removed, and re-installed google chrome, no change.

**Comment by BloodAsp** [comment]
I have BS4 version 4.9.3,  lxml version 4.6.2.0, urllib3 version 10.25.10, requests version 2.24.0, and selenium version 3.141.0.
Google Chrome did just update to 89.0.4389.82 (Official Build) (64-bit)
Still not functioning yet.  I got too tired to fully wipe and re-install tonight, I'll check it out tomorrow.

**Comment by BloodAsp** [comment]
I got around to tinkering with it just a bit, I didn't look at any logs as it was simple to set up again, I git cloned the project, transferred my account .json file, and ran it from the new folder.  It worked like a charm.  I re-tested the old folder, and it did not work, the files were never edited, and there were no differences.  So I dunno.  I just rm -r *, cp ~/.../* . , and it is up and running again.  I'll close out this 'issue' tomorrow when my crontab picks it up.     Sorry there was no good solution, ty for the offered help, and ty for the project!
